// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZq9CSZEfMCr6RZaPDH-Mfawxz_R6_q0g',
    appId: '1:831066053340:web:979ecf01807908b4703219',
    messagingSenderId: '831066053340',
    projectId: 'e-commerceapp-31594',
    authDomain: 'e-commerceapp-31594.firebaseapp.com',
    storageBucket: 'e-commerceapp-31594.appspot.com',
    measurementId: 'G-PFFWN8N8ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxc7gV7RYi65BnmIGu18EKLLJi8gCAMkU',
    appId: '1:831066053340:android:f01be934cd9641a2703219',
    messagingSenderId: '831066053340',
    projectId: 'e-commerceapp-31594',
    storageBucket: 'e-commerceapp-31594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfbC_A5uQ2-vq0JRWgyFUUNgjX-BAu08Q',
    appId: '1:831066053340:ios:9388edc567678c9b703219',
    messagingSenderId: '831066053340',
    projectId: 'e-commerceapp-31594',
    storageBucket: 'e-commerceapp-31594.appspot.com',
    androidClientId: '831066053340-gv40k8nk45ia9n2rcoh0omb16dpjv5k7.apps.googleusercontent.com',
    iosClientId: '831066053340-rtfe07jfinvjdovstmrd0ul9p2btfjgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommApp',
  );
}
